# Generated by Django 2.2.1 on 2021-10-24 17:42

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
