# Generated by Django 2.2.1 on 2021-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20211024_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preface',
        ),
    ]
