# Generated by Django 2.2.1 on 2021-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('origin', models.TextField(blank=True)),
                ('origin_author', models.CharField(blank=True, default='', max_length=200)),
                ('translate', models.TextField(blank=True)),
                ('translate_author', models.CharField(blank=True, default='', max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'translation',
            },
        ),
    ]
